### ISSUE TITLE
直接集成spring boot 即可

### ISSUE THREAD

**Issue by su-yh** [intsmaze/flink-boot#10]
我看了下，这个代码。
意义不大，而还用的是xml 格式的bean 加载，相当于回到石器时代了。
意义并不大，如果使用spring 的xml 格式，那我直接用原始的三方依赖不就好吗，还来这一套。
其实这里面的根本原因就是flink 的classload 加载的问题，我们只要使用flink 官方的方式，将三方依赖，存放到flink 指定的classload 的目录，也就是 flink-1.17.2/lib 目录下面就可以了，这里面的子目录都可以被访问到了。
另外 一个就是要注意，taskmanager 和jobmanager 是不同的进程，也就是不同的java 程序。
知道这个原理之后就可以很轻松的处理了。
有兴趣可以参考：https://github.com/su-yh/suyh-demo-flink/tree/develop/demo-01/d05-springboot

**Comment by intsmaze** [comment]
可以不喜欢，不认同，但不要随意发表评价以误人子弟。 第一xml只是开启bean扫描，配置bean还是依赖注解。第二 使用spring xml 还是要依赖 原始的三方依赖，我没明白你说的【如果使用spring 的xml 格式，那我直接用原始的三方依赖不就好吗】的意思，spring是用来干什么的可以先去了解一下。第三 【放flink-1.17.2/lib】 和打在可执行jar包 能为你改变什么？ 可以直接用spirng 注解了吗？ 第四 【放flink-1.17.2/lib】 是很随意放的吗？ 一个公司几十人都把自己的包放到 lib下，稳定性怎么解决，冲突怎么解决？ 如果flink集群就一个开发者运维和任务开发，你想怎么玩都可以，上了团队恐怕不能这样玩吧？最后一句【可以不喜欢，不认同，但不要随意发表评价以误人子弟。】

**Comment by intsmaze** [comment]
心怀善良才有好运

**Comment by intsmaze** [comment]
心怀善良才有好运
