### ISSUE TITLE
pom依赖缺失

### ISSUE THREAD

**Issue by jiajingsi** [intsmaze/flink-boot#2]
flink-base模块中，由于引入了druid，所以需要添加如下依赖：
<dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>druid</artifactId>
</dependency>

<dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
</dependency>

**Comment by intsmaze** [comment]
将druid的maven坐标由flink-mybatis工程移到flink-base工程进行配置
